### PR TITLE
Use Kirby’s email() function for sending comment notification emails

### PR DESCRIPTION
**Pull request by lumpysimon**
Hi

I've made a small change so that comment notification emails are sent with Kirby’s `email()` function instead of PHP’s `mail()` function. 

This makes it possible for users to specify their preferred mail service (e.g. SES, Postmark, etc), API keys and other email configuration options (as per https://getkirby.com/docs/developer-guide/advanced/emails).

(Apologies for all the changed blank lines, I think they are caused by my editor automatically stripping out trailing spaces)

### CODE REVIEW

**Comment by florianpircher** [comment]
Thank you for implementing this! I will test this feature and merge it once I am confident that it works as aspected.

**Comment by florianpircher** [comment]
Works great, but I don’t want to merge all of the whitespace-change-only lines. Please update this pull request or create a new pull request with only the significant lines changed if you want GitHub to track your contribution. If you don’t care about that, I will happily do that myself.

**Comment by lumpysimon** [comment]
Sure, happy to do that. I'll get it done later today or tomorrow.

**Comment by lumpysimon** [comment]
I've just pushed a commit that undoes all the whitespace changes.

**Review by florianpircher — APPROVED** [review]

**Comment by florianpircher** [comment]
Thank you for the contribution, this will be included in the next release.

**Pull request merged**
